[package]
name = "moirspy-copt"
version = "0.2.2"
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "moirspy_copt"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
numpy = "0.29.0"
moi-solver-copt.workspace = true
moi-bridge.workspace = true
moi-solver-api.workspace = true
moi-core.workspace = true
