import types
from typing import ClassVar, Iterable, List, Optional, Tuple, Union, overload

Number = Union[int, float]

class _VarType:
    pass

class _Sense:
    pass

class _MOI(types.ModuleType):
    CONTINUOUS: _VarType
    BINARY: _VarType
    INTEGER: _VarType
    MINIMIZE: _Sense
    MAXIMIZE: _Sense

MOI: _MOI

EnvConfigValue = Union[str, bool, int, float]

class COPT:
    CLIENT_CAFILE: ClassVar[str]
    CLIENT_CERTFILE: ClassVar[str]
    CLIENT_CERTKEYFILE: ClassVar[str]
    CLIENT_CLUSTER: ClassVar[str]
    CLIENT_FLOATING: ClassVar[str]
    CLIENT_PASSWORD: ClassVar[str]
    CLIENT_PORT: ClassVar[str]
    CLIENT_PRIORITY: ClassVar[str]
    CLIENT_WAITTIME: ClassVar[str]
    CLIENT_WEBSERVER: ClassVar[str]
    CLIENT_WEBLICENSEID: ClassVar[str]
    CLIENT_WEBACCESSKEY: ClassVar[str]
    CLIENT_WEBTOKENDURATION: ClassVar[str]

class CoptEnvConfig:
    def __init__(self, dll_path: Optional[str] = ...) -> None: ...
    def set(self, name: str, value: EnvConfigValue) -> None: ...

class CoptEnv:
    def __init__(
        self,
        dll_path: Optional[str] = ...,
        license_dir: Optional[str] = ...,
        config: Optional[CoptEnvConfig] = ...,
    ) -> None: ...

class GurobiEnv:
    def __init__(
        self, dll_path: Optional[str] = ..., empty: bool = ...
    ) -> None: ...
    def setParam(self, name: str, value: EnvConfigValue) -> None: ...
    def start(self) -> None: ...
    @property
    def started(self) -> bool: ...

class Constr:
    """A pending scalar linear constraint created by a comparison."""

class Var:
    def __init__(self, id: int) -> None: ...
    @property
    def X(self) -> Optional[float]: ...
    def __add__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __radd__(self, other: Number) -> LinExpr: ...
    def __sub__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __rsub__(self, other: Number) -> LinExpr: ...
    def __mul__(self, other: Number) -> LinExpr: ...
    def __rmul__(self, other: Number) -> LinExpr: ...
    def __le__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __ge__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __eq__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...  # type: ignore[override]
    def __str__(self) -> str: ...

class Vars:
    def __init__(self, shape: List[int], ids: List[int]) -> None: ...
    @overload
    def __getitem__(self, index: int) -> Var: ...
    @overload
    def __getitem__(self, index: Tuple[int, ...]) -> Var: ...
    @overload
    def __getitem__(self, index: List[int]) -> Var: ...
    def __str__(self) -> str: ...

class LinExpr:
    def __add__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __radd__(self, other: Number) -> LinExpr: ...
    def __sub__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __rsub__(self, other: Number) -> LinExpr: ...
    def __mul__(self, other: Number) -> LinExpr: ...
    def __rmul__(self, other: Number) -> LinExpr: ...
    def __le__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __ge__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __eq__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...  # type: ignore[override]
    def __str__(self) -> str: ...

class Model:
    def __init__(
        self,
        name: str,
        backend: Optional[str] = ...,
        env: Optional[Union[CoptEnv, GurobiEnv]] = ...,
    ) -> None: ...
    def addVar(
        self,
        lb: float = ...,
        ub: float = ...,
        obj: float = ...,
        vtype: Optional[_VarType] = ...,
        name: Optional[str] = ...,
    ) -> Var: ...
    def addVars(
        self,
        *indices: int,
        lb: Optional[Union[Number, List[float]]] = ...,
        ub: Optional[Union[Number, List[float]]] = ...,
        obj: Optional[Union[Number, List[float]]] = ...,
        vtype: Optional[Union[_VarType, List[_VarType]]] = ...,
        name: Optional[Union[str, List[str]]] = ...,
    ) -> Vars: ...
    def addConstr(self, constr: Constr, name: Optional[str] = ...) -> None: ...
    def addConstrs(
        self,
        generator: Iterable[Constr],
        name: Optional[Union[str, List[str]]] = ...,
    ) -> None: ...
    def setObjective(self, expr: LinExpr, sense: _Sense) -> None: ...
    def setParam(self, paramname: str, newvalue: Union[bool, int, float, str]) -> None: ...
    def setBackend(
        self,
        backend: str,
        env: Optional[Union[CoptEnv, GurobiEnv, object]] = ...,
        *,
        keep_cache: bool = ...,
    ) -> None: ...
    def optimize(self) -> None: ...
    def update(self) -> None: ...
    @property
    def ObjVal(self) -> Optional[float]: ...
    def __str__(self) -> str: ...

def quicksum(generator: Iterable[Union[Number, Var, LinExpr]]) -> LinExpr: ...
def dot(coefficients: Iterable[Number], variables: Iterable[Var]) -> LinExpr: ...
