import types
from typing import Iterable, List, Optional, Tuple, Union, overload

Number = Union[int, float]

class _VarType:
    pass

class _Sense:
    pass

class _MOI(types.ModuleType):
    CONTINUOUS: _VarType
    BINARY: _VarType
    INTEGER: _VarType
    MINIMIZE: _Sense
    MAXIMIZE: _Sense

MOI: _MOI

class Constr:
    """A pending scalar linear constraint created by a comparison."""

class Var:
    def __init__(self, id: int) -> None: ...
    @property
    def X(self) -> Optional[float]: ...
    def __add__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __radd__(self, other: Number) -> LinExpr: ...
    def __sub__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __rsub__(self, other: Number) -> LinExpr: ...
    def __mul__(self, other: Number) -> LinExpr: ...
    def __rmul__(self, other: Number) -> LinExpr: ...
    def __le__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __ge__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __eq__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...  # type: ignore[override]
    def __str__(self) -> str: ...

class Vars:
    def __init__(self, shape: List[int], ids: List[int]) -> None: ...
    @overload
    def __getitem__(self, index: int) -> Var: ...
    @overload
    def __getitem__(self, index: Tuple[int, ...]) -> Var: ...
    @overload
    def __getitem__(self, index: List[int]) -> Var: ...
    def __str__(self) -> str: ...

class LinExpr:
    def __add__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __radd__(self, other: Number) -> LinExpr: ...
    def __sub__(self, other: Union[Number, Var, LinExpr]) -> LinExpr: ...
    def __rsub__(self, other: Number) -> LinExpr: ...
    def __mul__(self, other: Number) -> LinExpr: ...
    def __rmul__(self, other: Number) -> LinExpr: ...
    def __le__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __ge__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...
    def __eq__(self, other: Union[Number, Var, LinExpr]) -> Constr: ...  # type: ignore[override]
    def __str__(self) -> str: ...

class Model:
    def __init__(self, name: str) -> None: ...
    def addVar(
        self,
        lb: float = ...,
        ub: float = ...,
        obj: float = ...,
        vtype: Optional[_VarType] = ...,
        name: str = ...,
    ) -> Var: ...
    def addVars(
        self,
        *indices: int,
        lb: Optional[Union[Number, List[float]]] = ...,
        ub: Optional[Union[Number, List[float]]] = ...,
        obj: Optional[Union[Number, List[float]]] = ...,
        vtype: Optional[Union[_VarType, List[_VarType]]] = ...,
        name: Optional[Union[str, List[str]]] = ...,
    ) -> Vars: ...
    def addConstr(self, constr: Constr, name: Optional[str] = ...) -> None: ...
    def addConstrs(
        self,
        generator: Iterable[Constr],
        name: Optional[Union[str, List[str]]] = ...,
    ) -> None: ...
    def setObjective(self, expr: LinExpr, sense: _Sense) -> None: ...
    def setParam(self, paramname: str, newvalue: Union[bool, int, float, str]) -> None: ...
    def setBackend(self, backend: str) -> None: ...
    def optimize(self) -> None: ...
    @property
    def ObjVal(self) -> Optional[float]: ...
    def __str__(self) -> str: ...

def quicksum(generator: Iterable[Union[Number, Var, LinExpr]]) -> LinExpr: ...
