[package]
name = "moirspy-gurobi"
version = "0.2.1"
edition.workspace = true
authors.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "moirspy_gurobi"
crate-type = ["cdylib"]

[dependencies]
pyo3.workspace = true
numpy = "0.29.0"
moi-solver-gurobi.workspace = true
moi-bridge.workspace = true
moi-solver-api.workspace = true
moi-core.workspace = true
